version: '2'  
services:
  nginx:
    image: nginx:latest
    container_name: nginx_api
    ports:
      - "8000:8000"
    volumes:
      - ./config:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: web_page
    # command: bash -c 'cd api && python api.py'
    command: bash -c 'cd api && gunicorn -w 4 api:app -b 0.0.0.0:8001'
    ports:
       - "8001:8001"
    expose:
      - "8000"
      - "8001"
