version: '2'  
services:
  nginx:
    image: nginx:latest
    container_name: nginx_api
    ports:
      - "80:8001"
    volumes:
      - ./config:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: web_page
    command: bash -c 'cd api && python api.py'
    ports:
       - "8001:8001"
    expose:
      - "8001"
      - "80"
